[default]
log_level = 'info'
log_format = '%(asctime)s [%(levelname)s] %(filename)s@%(lineno)s - %(funcName)s(): %(message)s'
log_size = 52428800

[flask]
host = '127.0.0.1'
port = 8800
debug = true

[mongodb]
url = 'mongodb://127.0.0.1:27017'
database = 'ituiniu'
auth = false
user = ''
pass = ''
replica_set = ''

[mysql]
NAME = 'plutus'
USER = 'root'
PASSWORD = 'root'
HOST = '127.0.0.1'
PORT = '3306'

[mysql.OPTIONS]
charset = 'utf8mb4'
